# Generated by Django 4.2.14 on 2024-08-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_slug_alter_recipe_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['created_on']},
        ),
    ]
